REPO_PATH="$(dirname $(realpath "${BASH_SOURCE[0]}"))"
GO_VERSION="$(cat go.mod | grep -Ei "go ([0-9\.]+)" | grep -oEi '[0-9\.]+')"
SDL_VERSION="3.2.8"
SDL_TAG="release-${SDL_VERSION}"
TMP_DIR="${REPO_PATH}/tmp"