REPO_PATH="$(dirname $(realpath "${BASH_SOURCE[0]}"))"
GO_VERSION="$(cat go.mod | grep -Ei "go ([0-9\.]+)" | grep -oEi '[0-9\.]+')"
SDL_VERSION="3.2.22"
SDL_TAG="release-${SDL_VERSION}"
SDL_IMAGE_VERSION="3.2.4"
SDL_IMAGE_TAG="release-${SDL_IMAGE_VERSION}"
TMP_DIR="${REPO_PATH}/tmp"
