package sdl

/*
#include <SDL3/SDL_keycode.h>
*/
import "C"

type Keymod uint16

const (
	KMOD_NONE   Keymod = C.SDL_KMOD_NONE
	KMOD_LSHIFT Keymod = C.SDL_KMOD_LSHIFT
	KMOD_RSHIFT Keymod = C.SDL_KMOD_RSHIFT
	KMOD_LCTRL  Keymod = C.SDL_KMOD_LCTRL
	KMOD_RCTRL  Keymod = C.SDL_KMOD_RCTRL
	KMOD_LALT   Keymod = C.SDL_KMOD_LALT
	KMOD_RALT   Keymod = C.SDL_KMOD_RALT
	KMOD_LGUI   Keymod = C.SDL_KMOD_LGUI
	KMOD_RGUI   Keymod = C.SDL_KMOD_RGUI
	KMOD_NUM    Keymod = C.SDL_KMOD_NUM
	KMOD_CAPS   Keymod = C.SDL_KMOD_CAPS
	KMOD_MODE   Keymod = C.SDL_KMOD_MODE
	KMOD_SCROLL Keymod = C.SDL_KMOD_SCROLL
	KMOD_CTRL   Keymod = C.SDL_KMOD_CTRL
	KMOD_SHIFT  Keymod = C.SDL_KMOD_SHIFT
	KMOD_ALT    Keymod = C.SDL_KMOD_ALT
	KMOD_GUI    Keymod = C.SDL_KMOD_GUI
)
