package sdl

/*
#include <SDL3/SDL_pixels.h>

static inline Uint8 _SDL_BytesPerPixel(SDL_PixelFormat pixelFormat) {
	return SDL_BYTESPERPIXEL(pixelFormat);
}
*/
import "C"

type Palette C.SDL_Palette
type PixelFormat C.SDL_PixelFormat
type PixelFormatDetails C.SDL_PixelFormatDetails

const (
	ALPHA_OPAQUE            uint8   = C.SDL_ALPHA_OPAQUE
	ALPHA_OPAQUE_FLOAT      float32 = C.SDL_ALPHA_OPAQUE_FLOAT
	ALPHA_TRANSPARENT       uint8   = C.SDL_ALPHA_TRANSPARENT
	ALPHA_TRANSPARENT_FLOAT float32 = C.SDL_ALPHA_TRANSPARENT_FLOAT

	PIXELFORMAT_UNKNOWN       PixelFormat = C.SDL_PIXELFORMAT_UNKNOWN
	PIXELFORMAT_INDEX1LSB     PixelFormat = C.SDL_PIXELFORMAT_INDEX1LSB
	PIXELFORMAT_INDEX1MSB     PixelFormat = C.SDL_PIXELFORMAT_INDEX1MSB
	PIXELFORMAT_INDEX2LSB     PixelFormat = C.SDL_PIXELFORMAT_INDEX2LSB
	PIXELFORMAT_INDEX2MSB     PixelFormat = C.SDL_PIXELFORMAT_INDEX2MSB
	PIXELFORMAT_INDEX4LSB     PixelFormat = C.SDL_PIXELFORMAT_INDEX4LSB
	PIXELFORMAT_INDEX4MSB     PixelFormat = C.SDL_PIXELFORMAT_INDEX4MSB
	PIXELFORMAT_INDEX8        PixelFormat = C.SDL_PIXELFORMAT_INDEX8
	PIXELFORMAT_RGB332        PixelFormat = C.SDL_PIXELFORMAT_RGB332
	PIXELFORMAT_XRGB4444      PixelFormat = C.SDL_PIXELFORMAT_XRGB4444
	PIXELFORMAT_XBGR4444      PixelFormat = C.SDL_PIXELFORMAT_XBGR4444
	PIXELFORMAT_XRGB1555      PixelFormat = C.SDL_PIXELFORMAT_XRGB1555
	PIXELFORMAT_XBGR1555      PixelFormat = C.SDL_PIXELFORMAT_XBGR1555
	PIXELFORMAT_ARGB4444      PixelFormat = C.SDL_PIXELFORMAT_ARGB4444
	PIXELFORMAT_RGBA4444      PixelFormat = C.SDL_PIXELFORMAT_RGBA4444
	PIXELFORMAT_ABGR4444      PixelFormat = C.SDL_PIXELFORMAT_ABGR4444
	PIXELFORMAT_BGRA4444      PixelFormat = C.SDL_PIXELFORMAT_BGRA4444
	PIXELFORMAT_ARGB1555      PixelFormat = C.SDL_PIXELFORMAT_ARGB1555
	PIXELFORMAT_RGBA5551      PixelFormat = C.SDL_PIXELFORMAT_RGBA5551
	PIXELFORMAT_ABGR1555      PixelFormat = C.SDL_PIXELFORMAT_ABGR1555
	PIXELFORMAT_BGRA5551      PixelFormat = C.SDL_PIXELFORMAT_BGRA5551
	PIXELFORMAT_RGB565        PixelFormat = C.SDL_PIXELFORMAT_RGB565
	PIXELFORMAT_BGR565        PixelFormat = C.SDL_PIXELFORMAT_BGR565
	PIXELFORMAT_RGB24         PixelFormat = C.SDL_PIXELFORMAT_RGB24
	PIXELFORMAT_BGR24         PixelFormat = C.SDL_PIXELFORMAT_BGR24
	PIXELFORMAT_XRGB8888      PixelFormat = C.SDL_PIXELFORMAT_XRGB8888
	PIXELFORMAT_RGBX8888      PixelFormat = C.SDL_PIXELFORMAT_RGBX8888
	PIXELFORMAT_XBGR8888      PixelFormat = C.SDL_PIXELFORMAT_XBGR8888
	PIXELFORMAT_BGRX8888      PixelFormat = C.SDL_PIXELFORMAT_BGRX8888
	PIXELFORMAT_ARGB8888      PixelFormat = C.SDL_PIXELFORMAT_ARGB8888
	PIXELFORMAT_RGBA8888      PixelFormat = C.SDL_PIXELFORMAT_RGBA8888
	PIXELFORMAT_ABGR8888      PixelFormat = C.SDL_PIXELFORMAT_ABGR8888
	PIXELFORMAT_BGRA8888      PixelFormat = C.SDL_PIXELFORMAT_BGRA8888
	PIXELFORMAT_XRGB2101010   PixelFormat = C.SDL_PIXELFORMAT_XRGB2101010
	PIXELFORMAT_XBGR2101010   PixelFormat = C.SDL_PIXELFORMAT_XBGR2101010
	PIXELFORMAT_ARGB2101010   PixelFormat = C.SDL_PIXELFORMAT_ARGB2101010
	PIXELFORMAT_ABGR2101010   PixelFormat = C.SDL_PIXELFORMAT_ABGR2101010
	PIXELFORMAT_RGB48         PixelFormat = C.SDL_PIXELFORMAT_RGB48
	PIXELFORMAT_BGR48         PixelFormat = C.SDL_PIXELFORMAT_BGR48
	PIXELFORMAT_RGBA64        PixelFormat = C.SDL_PIXELFORMAT_RGBA64
	PIXELFORMAT_ARGB64        PixelFormat = C.SDL_PIXELFORMAT_ARGB64
	PIXELFORMAT_BGRA64        PixelFormat = C.SDL_PIXELFORMAT_BGRA64
	PIXELFORMAT_ABGR64        PixelFormat = C.SDL_PIXELFORMAT_ABGR64
	PIXELFORMAT_RGB48_FLOAT   PixelFormat = C.SDL_PIXELFORMAT_RGB48_FLOAT
	PIXELFORMAT_BGR48_FLOAT   PixelFormat = C.SDL_PIXELFORMAT_BGR48_FLOAT
	PIXELFORMAT_RGBA64_FLOAT  PixelFormat = C.SDL_PIXELFORMAT_RGBA64_FLOAT
	PIXELFORMAT_ARGB64_FLOAT  PixelFormat = C.SDL_PIXELFORMAT_ARGB64_FLOAT
	PIXELFORMAT_BGRA64_FLOAT  PixelFormat = C.SDL_PIXELFORMAT_BGRA64_FLOAT
	PIXELFORMAT_ABGR64_FLOAT  PixelFormat = C.SDL_PIXELFORMAT_ABGR64_FLOAT
	PIXELFORMAT_RGB96_FLOAT   PixelFormat = C.SDL_PIXELFORMAT_RGB96_FLOAT
	PIXELFORMAT_BGR96_FLOAT   PixelFormat = C.SDL_PIXELFORMAT_BGR96_FLOAT
	PIXELFORMAT_RGBA128_FLOAT PixelFormat = C.SDL_PIXELFORMAT_RGBA128_FLOAT
	PIXELFORMAT_ARGB128_FLOAT PixelFormat = C.SDL_PIXELFORMAT_ARGB128_FLOAT
	PIXELFORMAT_BGRA128_FLOAT PixelFormat = C.SDL_PIXELFORMAT_BGRA128_FLOAT
	PIXELFORMAT_ABGR128_FLOAT PixelFormat = C.SDL_PIXELFORMAT_ABGR128_FLOAT
	PIXELFORMAT_YV12          PixelFormat = C.SDL_PIXELFORMAT_YV12
)

func BytesPerPixel(format PixelFormat) uint8 {
	return (uint8)(C._SDL_BytesPerPixel((C.SDL_PixelFormat)(format)))
}

func GetPixelFormatDetails(format PixelFormat) (*PixelFormatDetails, error) {
	result := (*PixelFormatDetails)(
		C.SDL_GetPixelFormatDetails(
			(C.SDL_PixelFormat)(format),
		),
	)

	return result, mapErrorPointer(result)
}

func MapRGB(format *PixelFormatDetails, palette *Palette, r uint8, g uint8, b uint8) uint32 {
	return uint32(
		C.SDL_MapRGB(
			(*C.SDL_PixelFormatDetails)(format),
			(*C.SDL_Palette)(palette),
			(C.Uint8)(r),
			(C.Uint8)(g),
			(C.Uint8)(b),
		),
	)
}
