package sdl

//#include "pixels.h"
import "C"

const (
	ALPHA_OPAQUE            uint8   = C.SDL_ALPHA_OPAQUE
	ALPHA_OPAQUE_FLOAT      float32 = C.SDL_ALPHA_OPAQUE_FLOAT
	ALPHA_TRANSPARENT       uint8   = C.SDL_ALPHA_TRANSPARENT
	ALPHA_TRANSPARENT_FLOAT float32 = C.SDL_ALPHA_TRANSPARENT_FLOAT
)
