name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: 1
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
      - name: Install SDL
        run: sudo apt install -y libsdl2-dev
      - name: Build
        run: make build