name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: 1
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./scripts/docker-run.sh "make build"
      - name: Build Examples
        run: ./scripts/docker-run.sh "make build-examples"      

          