name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: 1
jobs:
  ci:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: smack0007/sdl-go
          options: -v ${{ github.workspace }}:/app -e CI=1
          run: make build