name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: 1
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./scripts/docker-run.sh "make build"
      - name: Build Examples
        run: ./scripts/docker-run.sh "make build-examples"
      - name: Build sdl-go-template
        run: |
          git clone --depth=1 https://github.com/smack0007/sdl-go-template.git ../sdl-go-template
          DOCKER_FLAGS="-v ${PWD}/../sdl-go-template:/data/sdl-go-template -w /data/sdl-go-template" ./scripts/docker-run.sh "make build" 
          